// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaProgramada2_JuanDiegoSanchez.AppDbContext;

#nullable disable

namespace PracticaProgramada2_JuanDiegoSanchez.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240626215048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Lista", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLista"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdLista");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLista")
                        .HasColumnType("int");

                    b.Property<int>("ListasIdLista")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("bit");

                    b.HasKey("IdTarea");

                    b.HasIndex("ListasIdLista");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Lista", b =>
                {
                    b.HasOne("PracticaProgramada2_JuanDiegoSanchez.Models.Usuario", null)
                        .WithMany("Listas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Tarea", b =>
                {
                    b.HasOne("PracticaProgramada2_JuanDiegoSanchez.Models.Lista", "Listas")
                        .WithMany("Tareas")
                        .HasForeignKey("ListasIdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listas");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Lista", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PracticaProgramada2_JuanDiegoSanchez.Models.Usuario", b =>
                {
                    b.Navigation("Listas");
                });
#pragma warning restore 612, 618
        }
    }
}
